# Generated by Django 4.2.13 on 2026-06-03 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('icon', models.ImageField(blank=True, help_text='Category icon for bot display', null=True, upload_to='category_icons/')),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail for preview', null=True, upload_to='category_thumbnails/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within parent category')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide category in bot')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this category in main menu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchy', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.category')),
            ],
            options={
                'db_table': 'content_category',
                'ordering': ['parent', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Content title', max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly identifier')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('link', 'Link'), ('quiz', 'Quiz')], default='text', help_text='Type of content', max_length=20)),
                ('description', models.TextField(help_text='Short description for preview')),
                ('body', models.TextField(help_text='Main content (supports markdown)')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for search', max_length=500)),
                ('image', models.ImageField(blank=True, help_text='Featured image', null=True, upload_to='content_images/')),
                ('media_url', models.URLField(blank=True, help_text='External media URL (video, audio, etc.)')),
                ('file', models.FileField(blank=True, help_text='Downloadable file', null=True, upload_to='content_files/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('is_active', models.BooleanField(default=True, help_text='Publish/unpublish content')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature in category')),
                ('views_count', models.PositiveIntegerField(default=0, help_text='Number of views')),
                ('is_premium', models.BooleanField(default=False, help_text='Only for paid users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date', null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_content', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='Parent category', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.category')),
            ],
            options={
                'db_table': 'content_content',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Telegram/WhatsApp user ID', max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating from 1 to 5 stars')),
                ('comment', models.TextField(blank=True, help_text='User feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.content')),
            ],
            options={
                'db_table': 'content_rating',
                'ordering': ['-created_at'],
                'unique_together': {('content', 'user_id')},
            },
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category', 'is_active'], name='content_con_categor_fb4338_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['slug', 'category'], name='content_con_slug_78f189_idx'),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['-created_at'], name='content_con_created_70bf4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('category', 'slug')},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='content_cat_parent__21c13f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='content_cat_slug_d6cc3e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='content_cat_is_acti_04babc_idx'),
        ),
    ]
