# Generated by Django 4.2.13 on 2026-06-09 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Additional categories/tags for this content', related_name='tagged_contents', to='content.category'),
        ),
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(help_text='Primary category', on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content.category'),
        ),
    ]
