# Generated by Django 4.2.13 on 2026-06-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_content_categories_alter_content_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['parent_id', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='inline_display',
            field=models.BooleanField(default=False, help_text='Show subcategories as inline buttons (single row) instead of stacked'),
        ),
    ]
