# Generated by Django 4.2.13 on 2026-06-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_category_options_category_inline_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cta_message',
            field=models.CharField(blank=True, help_text="Call-to-action message shown when this category's subcategories are displayed (e.g. 'Choose country:')", max_length=500),
        ),
    ]
