# Generated by Django 4.2.13 on 2026-06-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_category_cta_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expand_children_inline',
            field=models.BooleanField(default=True, help_text='Show children in the same message below parent buttons (True) or send as a new message (False)'),
        ),
    ]
