# Generated by Django 4.2.13 on 2026-06-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_tag_category_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tags',
        ),
    ]
