# Generated by Django 4.2.13 on 2026-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_remove_category_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, help_text='Business logo', null=True, upload_to='business_logos/')),
                ('title', models.CharField(help_text='Business name', max_length=300)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('geo_coordinates', models.CharField(blank=True, help_text='Coordinates (lat,lng) — auto-detected from address but can be edited', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Business description')),
                ('online_store', models.URLField(blank=True, help_text='Online store URL')),
                ('facebook', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL')),
                ('tiktok', models.URLField(blank=True, help_text='TikTok URL')),
                ('youtube', models.URLField(blank=True, help_text='YouTube URL')),
                ('hotline', models.CharField(blank=True, help_text='Hotline phone number', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_active', models.BooleanField(default=True, help_text='Publish/unpublish')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Associated categories', related_name='businesses', to='content.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Country tags', related_name='businesses', to='content.tag')),
            ],
            options={
                'db_table': 'content_business',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
