# Generated by Django 4.2.13 on 2026-06-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_flag',
            field=models.BooleanField(default=True, help_text='Show flag emoji / tag flag at the start of the category name in the bot'),
        ),
    ]
