# Generated by Django 4.2.13 on 2026-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_category_show_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='emoji',
            field=models.CharField(blank=True, default='🎁', help_text='Emoji shown before the business name in bot lists (leave blank to hide)', max_length=10),
        ),
    ]
