# Generated by Django 4.2.13 on 2026-06-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_business_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='hotline_label',
            field=models.CharField(blank=True, default='Гаряча лінія', help_text='Label for the hotline button', max_length=100),
        ),
    ]
