# Generated by Django 4.2.13 on 2026-06-03 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_token', models.CharField(help_text='Telegram bot token from BotFather', max_length=500)),
                ('telegram_nickname', models.CharField(default='ContentMentor', help_text='Bot username/nickname (without @)', max_length=100, unique=True)),
                ('whatsapp_phone_number', models.CharField(blank=True, help_text='WhatsApp Business Account phone number', max_length=20, null=True)),
                ('whatsapp_api_key', models.CharField(blank=True, help_text='WhatsApp API key from Twilio or provider', max_length=500, null=True)),
                ('access_mode', models.CharField(choices=[('public', 'Public - Anyone can access'), ('private', 'Private - Only whitelisted users'), ('paid', 'Paid - Subscription/payment required'), ('test', 'Test - Limited access for testing')], default='public', help_text='Access control mode for the bot', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable the bot')),
                ('description', models.TextField(blank=True, help_text='Bot description and purpose')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Bot Settings',
                'db_table': 'core_bot_settings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('access', 'Access')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'), models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx')],
            },
        ),
    ]
