# Generated by Django 4.2.13 on 2026-06-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='authorized_welcome_message',
            field=models.TextField(default='✨ Вас вітає InsiderKids — навіатор у світі індустрії дитячих товарів і розвиток !\n\n📢 Підписуйтесь, щоб не пропустити головне:\n🔔 InsiderKidsNews\nhttps://t.me/InsiderKidsNews\n\n📍 тренди | новини | огляди | події\n📱 Все найцікавіше в одній стрічці', help_text='Welcome message for authorized users'),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='unauthorized_welcome_message',
            field=models.TextField(default='The project is under development.', help_text='Message shown to unauthorized users'),
        ),
    ]
