# Generated by Django 4.2.13 on 2026-06-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botsettings_authorized_welcome_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='root_cta_message',
            field=models.CharField(default='Choose category:', help_text='Call-to-action message shown at the main menu (above top-level categories)', max_length=500),
        ),
    ]
