# Generated by Django 4.2.13 on 2026-06-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_botsettings_root_cta_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='show_tag_flag_on_categories',
            field=models.BooleanField(default=False, help_text="Prepend the selected tag's flag to category names displayed in the bot"),
        ),
    ]
