# Generated by Django 4.2.13 on 2026-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_botsettings_show_tag_flag_on_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='back_button_text',
            field=models.CharField(default='🔙 Back', help_text="Text for the 'Back' navigation button", max_length=100),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='main_menu_button_text',
            field=models.CharField(default='🏠 Main menu', help_text="Text for the 'Main menu' navigation button", max_length=100),
        ),
    ]
