# Generated by Django 4.2.13 on 2026-06-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_botsettings_back_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='tags_prompt_text',
            field=models.CharField(default='🌍 Choose a country:', help_text='Prompt text shown above the tag/country selection', max_length=200),
        ),
    ]
