# Generated by Django 4.2.13 on 2026-06-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_botsettings_tags_prompt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='welcome_image',
            field=models.ImageField(blank=True, help_text='Image sent with the welcome message', null=True, upload_to='welcome_images/'),
        ),
    ]
