# Generated by Django 4.2.13 on 2026-06-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='Telegram or WhatsApp user ID', max_length=100, unique=True)),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('both', 'Both Platforms')], default='telegram', help_text='Which platform the user is from', max_length=20)),
                ('username', models.CharField(blank=True, help_text="User's display name/username", max_length=255)),
                ('phone', models.CharField(blank=True, help_text="User's phone number", max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Allow/block user access')),
                ('is_premium', models.BooleanField(default=False, help_text='Premium/paid access granted')),
                ('is_whitelisted', models.BooleanField(default=False, help_text='Allowed in private mode')),
                ('first_interaction', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('interaction_count', models.PositiveIntegerField(default=0, help_text='Number of interactions with bot')),
                ('premium_until', models.DateTimeField(blank=True, help_text='Premium access expiration date', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about user')),
            ],
            options={
                'db_table': 'access_control_bot_user',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name (e.g., 'Basic', 'Pro', 'Premium')", max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('duration_days', models.PositiveIntegerField(help_text='Duration in days')),
                ('features', models.JSONField(default=list, help_text='List of included features')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'access_control_subscription_plan',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment provider transaction ID', max_length=200)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='access_control.botuser')),
            ],
            options={
                'db_table': 'access_control_user_subscription',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCategoryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_allowed', models.BooleanField(default=True, help_text='Allow/deny access to this category')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Temporary access expiration', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='content.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_access', to='access_control.botuser')),
            ],
            options={
                'db_table': 'access_control_user_category_access',
            },
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['user_id'], name='access_cont_user_id_e4663a_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['platform'], name='access_cont_platfor_158215_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['is_active'], name='access_cont_is_acti_8eedea_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['is_premium'], name='access_cont_is_prem_0bdec6_idx'),
        ),
        migrations.AddIndex(
            model_name='botuser',
            index=models.Index(fields=['-last_interaction'], name='access_cont_last_in_e1cb40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercategoryaccess',
            unique_together={('user', 'category')},
        ),
    ]
